package com.ilicitan_airlines.backend.dto.user;

import com.ilicitan_airlines.backend.entity.user.structure.*;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import lombok.*;
import java.time.Instant;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Schema(description = "DTO representing the full user profile information")
public class UserDTO {
    @Schema(description = "Unique autogenerated identifier of the user")
    private String id;

    @NotBlank(message = "Email is required")
    @Email(message = "Invalid email format")
    @Size(max = 255, message = "Email cannot exceed 255 characters")
    @Schema(description = "Email address used for authentication", example = "john.doe@example.com")
    private String email;

    @NotBlank(message = "Name is required")
    @Size(min = 2, max = 64, message = "Name must be between 2 and 64 characters")
    @Schema(description = "User's first name", example = "John")
    private String name;

    @NotBlank(message = "Surname is required")
    @Size(min = 2, max = 128, message = "Surname must be between 2 and 128 characters")
    @Schema(description = "User's surname", example = "Doe")
    private String surname;

    @Valid
    @NotNull(message = "Passport data is required")
    @Schema(description = "Passport identification details")
    private Passport passport;

    @Valid
    @NotNull(message = "Phone data is required")
    @Schema(description = "Contact phone information")
    private Phone phone;

    @NotNull(message = "Birth date is required")
    @Past(message = "Birth date must be in the past")
    @Schema(description = "User's date of birth in ISO-8601 format", example = "1990-05-15T00:00:00Z")
    private Instant birthDate;

    @NotNull(message = "Sex is required")
    @Schema(description = "User's biological sex", example = "MALE")
    private Sex sex;

    @Schema(description = "Current accumulated loyalty miles", example = "1500")
    private Integer miles;

    @Schema(description = "Provider used for authentication", example = "LOCAL")
    private String authProvider;
}